//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HockeyTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HockeyTracker.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPivotTitle {
            get {
                return ResourceManager.GetString("AboutPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app!.
        /// </summary>
        public static string AboutRateThisApp {
            get {
                return ResourceManager.GetString("AboutRateThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string AboutSendFeedback {
            get {
                return ResourceManager.GetString("AboutSendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application lets you receive instant notifications for specific events in NHL hockey games..
        /// </summary>
        public static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also pin live tiles for your favorite teams. Tiles show you the current score or when the next game starts..
        /// </summary>
        public static string AboutText2 {
            get {
                return ResourceManager.GetString("AboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantic.
        /// </summary>
        public static string DivisionAtlantic {
            get {
                return ResourceManager.GetString("DivisionAtlantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central.
        /// </summary>
        public static string DivisionCentral {
            get {
                return ResourceManager.GetString("DivisionCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metropolitan.
        /// </summary>
        public static string DivisionMetropolitan {
            get {
                return ResourceManager.GetString("DivisionMetropolitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific.
        /// </summary>
        public static string DivisionPacific {
            get {
                return ResourceManager.GetString("DivisionPacific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eastern.
        /// </summary>
        public static string EasternPivotTitle {
            get {
                return ResourceManager.GetString("EasternPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to against {0}.
        /// </summary>
        public static string GameAgainstTeam {
            get {
                return ResourceManager.GetString("GameAgainstTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losing {0}-{1}.
        /// </summary>
        public static string GameLosing {
            get {
                return ResourceManager.GetString("GameLosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost {0}-{1}.
        /// </summary>
        public static string GameLost {
            get {
                return ResourceManager.GetString("GameLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tied.
        /// </summary>
        public static string GameTied {
            get {
                return ResourceManager.GetString("GameTied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning {0}-{1}.
        /// </summary>
        public static string GameWinning {
            get {
                return ResourceManager.GetString("GameWinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won {0}-{1}.
        /// </summary>
        public static string GameWon {
            get {
                return ResourceManager.GetString("GameWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game in {0} min.
        /// </summary>
        public static string MinutesUntilGame {
            get {
                return ResourceManager.GetString("MinutesUntilGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every goal.
        /// </summary>
        public static string NotificationsEveryGoal {
            get {
                return ResourceManager.GetString("NotificationsEveryGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final scores.
        /// </summary>
        public static string NotificationsFinalScores {
            get {
                return ResourceManager.GetString("NotificationsFinalScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live tile.
        /// </summary>
        public static string NotificationsLiveTile {
            get {
                return ResourceManager.GetString("NotificationsLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a live tile on your start screen for this team. Updates during games..
        /// </summary>
        public static string NotificationsLiveTileExplanation {
            get {
                return ResourceManager.GetString("NotificationsLiveTileExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which notifications would you like to receive?.
        /// </summary>
        public static string NotificationsPageText {
            get {
                return ResourceManager.GetString("NotificationsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample:.
        /// </summary>
        public static string NotificationsSample {
            get {
                return ResourceManager.GetString("NotificationsSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadiens GOAL! Gionta, B. (4:20 in 3rd).
        /// </summary>
        public static string NotificationsSampleGoal {
            get {
                return ResourceManager.GetString("NotificationsSampleGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} WIN IN OT! {1} 5 - {2} 4.
        /// </summary>
        public static string SampleFinalScore {
            get {
                return ResourceManager.GetString("SampleFinalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to western.
        /// </summary>
        public static string WesternPivotTitle {
            get {
                return ResourceManager.GetString("WesternPivotTitle", resourceCulture);
            }
        }
    }
}
